# Generated by Django 3.1 on 2020-08-26 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_blacklistitem_blacklisttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='blacklistitem',
            name='name_slug',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='blacklistitem',
            name='image',
            field=models.ImageField(null=True, upload_to='bl/', verbose_name='Изображение превью 330x260)'),
        ),
    ]
