# Generated by Django 3.1 on 2020-08-26 18:59

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200826_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='blacklistitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Создана'),
        ),
        migrations.AddField(
            model_name='blacklistitem',
            name='details',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Детали.'),
        ),
        migrations.AddField(
            model_name='blacklistitem',
            name='proofs',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Доказаьельства.'),
        ),
    ]
